Wordle Codebase
Stevens-SSE/wordle-group-b pull request #1
Opened 2022-04-08 05:25 UTC by shivaniraykar

2022-04-13 19:55 UTC, jaiminbd13 commented on helper.py
> +from linkedlist import LinkedList
It's showing me no module named linked list.

2022-04-13 19:55 UTC, jaiminbd13 commented on helper.py
> +from linkedlist import LinkedList
It's showing me no module named linked list.

2022-04-13 20:16 UTC, shivaniraykar commented on helper.py
> +from linkedlist import LinkedList
Hey thanks for your comment, I guess you need to change the working directory and just run wordle.py, that's my main file. It will run on its own taking the words based on statistics file

2022-04-13 20:23 UTC, jaiminbd13 commented on dictionary.py
> +    def getRandomWord(self, selectedWordList) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

2022-04-13 20:24 UTC, jaiminbd13 commented on linkedlist.py
> +
Great job...!!

2022-04-13 20:34 UTC, jaiminbd13 commented on statistics.py
> +
Nicely done...!! Each nd every functions and syntax defined well.

2022-04-13 20:36 UTC, jaiminbd13 commented on ui.py
> +from exceptions import InvalidWord, LengthNotFiveAndAlphabets, SameInput
Showing me that  ModuleNotFoundError: No module named 'exceptions'

2022-04-13 20:39 UTC, shivaniraykar commented on ui.py
> +from exceptions import InvalidWord, LengthNotFiveAndAlphabets, SameInput
Hey, I guess you need to change the directory. If you check all the files, exception file does exist.

2022-04-13 20:44 UTC, shivaniraykar commented on ui.py
> +from exceptions import InvalidWord, LengthNotFiveAndAlphabets, SameInput
https://github.com/Stevens-SSE/wordle-group-b/pull/1/files

you can check all the files in the above link

2022-04-13 20:59 UTC, jaiminbd13 commented on ui.py
> +from exceptions import InvalidWord, LengthNotFiveAndAlphabets, SameInput
hey, Thanks for suggesting or letting me know this but earlier in my IDE Spyder it showed me like that way so. Tried in other IDE now I got it. 
well the code works well.

2022-04-13 21:11 UTC, jaiminbd13 commented on exceptions.py
> +
Excellent work..!

2022-04-13 21:23 UTC, jaiminbd13 commented
All and over, The code looks great to me also each comments are indicated so perfect and easy to understand the syntax as well as functions are defined so clearly with their proper names. there are minor changes needed like type error and its looks good but one more time cross verify that all the module imported/defined properly or not. Rest of the all codes looks excellent and done a very commendable work by you.

2022-04-13 22:35 UTC, deka1105 commented on dictionary.py
> +
Good to initialize blank variables, avoids false iterations

2022-04-13 22:36 UTC, deka1105 commented on gameplay.log
> +Game distribution for 6 = 0.0
Having a sample result helps to vizualize the outcome. Great addition!

2022-04-13 22:37 UTC, deka1105 commented on helper.py
> +from linkedlist import LinkedList
this might be dumb suggestion, but try pip install linkedlist or something similar

2022-04-13 22:38 UTC, deka1105 commented on helper.py
> +
I understand wanting to keep a piece of old code, to reference it in future. But try to avoid that if you are using Git regularly.

2022-04-13 22:41 UTC, deka1105 commented on ui.py
> +
Great use of raise, I have never tried before.

2022-04-13 22:42 UTC, deka1105 commented on wordle.py
> +            word_dict = self.dict.word_dict
I always emphasize on having blank variables rather than storing values to a new variables.

2022-04-13 22:44 UTC, deka1105 commented on helper.py
> +                            continue
Nice idea to use strip, many just use indexes

2022-04-13 22:44 UTC, deka1105 requested changes
One of the best codes I have reviewed so far.
Complete and well maintained

2022-04-19 17:44 UTC, shivaniraykar commented on helper.py
> +from linkedlist import LinkedList
You have to change the directory before you run the file

2022-04-19 17:47 UTC, shivaniraykar commented on dictionary.py
> +    def getRandomWord(self, selectedWordList) -> str | None:
Removed it!

2022-04-19 17:47 UTC, shivaniraykar commented on exceptions.py
> +
Thanks

2022-04-19 17:47 UTC, shivaniraykar commented on dictionary.py
> +
Thanks!

2022-04-19 17:47 UTC, shivaniraykar commented on helper.py
> +
Sure

2022-04-19 17:58 UTC, shivaniraykar commented on statistics.py
> +
Changed

2022-04-19 17:58 UTC, shivaniraykar commented on ui.py
> +
Thanks

2022-04-19 17:58 UTC, shivaniraykar commented on wordle.py
> +            word_dict = self.dict.word_dict
Thanks for the suggestion

2022-04-19 17:58 UTC, shivaniraykar commented on gameplay.log
> +Game distribution for 6 = 0.0
Thanks!

2022-04-19 18:03 UTC, merged